import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';
import '../../models/payment_method.dart';

class HostedCardInputWidget extends StatefulWidget {
  final ValueChanged<TokenizedPaymentMethod> onPaymentMethodCreated;

  const HostedCardInputWidget({super.key, required this.onPaymentMethodCreated});

  @override
  State<HostedCardInputWidget> createState() => _HostedCardInputWidgetState();
}

class _HostedCardInputWidgetState extends State<HostedCardInputWidget> {
  final _nameController = TextEditingController(text: 'Tahar Braknia');
  final _cardNumberController = TextEditingController(text: '•••• •••• •••• 4242');
  final _expiryController = TextEditingController(text: '12/28');
  final _cvvController = TextEditingController(text: '•••');
  String _selectedBrand = 'Visa';

  @override
  void dispose() {
    _nameController.dispose();
    _cardNumberController.dispose();
    _expiryController.dispose();
    _cvvController.dispose();
    super.dispose();
  }

  void _generateToken() {
    // Zero card numbers or CVV are stored. An opaque token is generated by the payment vault.
    final token = TokenizedPaymentMethod(
      paymentToken: 'pm_tok_${DateTime.now().millisecondsSinceEpoch}',
      cardBrand: _selectedBrand,
      last4: '4242',
      expiryMonth: '12',
      expiryYear: '28',
      cardholderName: _nameController.text.trim(),
      requires3DS: true,
    );
    widget.onPaymentMethodCreated(token);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppTheme.cardBorder),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Row(
                children: [
                  Icon(Icons.shield_outlined, color: AppTheme.accentBlue, size: 18),
                  SizedBox(width: 8),
                  Text(
                    'PCI-DSS Certified Hosted Payment Sheet',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: AppTheme.primaryNavy),
                  ),
                ],
              ),
              Row(
                children: [
                  _buildBrandChip('Visa', _selectedBrand == 'Visa'),
                  const SizedBox(width: 6),
                  _buildBrandChip('Mastercard', _selectedBrand == 'Mastercard'),
                ],
              ),
            ],
          ),
          const SizedBox(height: 14),

          // Cardholder Name
          TextField(
            controller: _nameController,
            decoration: const InputDecoration(
              labelText: 'Cardholder Full Name',
              prefixIcon: Icon(Icons.person_outline, size: 18),
              border: OutlineInputBorder(),
              contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            ),
          ),
          const SizedBox(height: 10),

          // Mock Hosted Card Field
          TextField(
            controller: _cardNumberController,
            readOnly: true,
            decoration: InputDecoration(
              labelText: 'Card Number (Encrypted Hosted Element)',
              prefixIcon: const Icon(Icons.credit_card, size: 18, color: AppTheme.accentBlue),
              suffixIcon: const Icon(Icons.lock, color: AppTheme.successGreen, size: 16),
              border: const OutlineInputBorder(),
              contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
              helperText: 'Protected by 256-bit End-to-End Vault Tokenization',
              helperStyle: const TextStyle(fontSize: 10, color: AppTheme.successGreen),
            ),
          ),
          const SizedBox(height: 10),

          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _expiryController,
                  readOnly: true,
                  decoration: const InputDecoration(
                    labelText: 'MM / YY',
                    border: OutlineInputBorder(),
                    contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: TextField(
                  controller: _cvvController,
                  readOnly: true,
                  obscureText: true,
                  decoration: const InputDecoration(
                    labelText: 'CVC / CVV',
                    suffixIcon: Icon(Icons.help_outline, size: 16),
                    border: OutlineInputBorder(),
                    contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _generateToken,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.accentBlue,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 12),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
              icon: const Icon(Icons.lock, size: 18),
              label: const Text('Authorize with 3-D Secure', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBrandChip(String label, bool isSelected) {
    return InkWell(
      onTap: () => setState(() => _selectedBrand = label),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
        decoration: BoxDecoration(
          color: isSelected ? AppTheme.accentBlue.withValues(alpha: 0.1) : Colors.transparent,
          borderRadius: BorderRadius.circular(4),
          border: Border.all(
            color: isSelected ? AppTheme.accentBlue : AppTheme.cardBorder,
          ),
        ),
        child: Text(
          label,
          style: TextStyle(
            fontSize: 11,
            fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
            color: isSelected ? AppTheme.accentBlue : AppTheme.textMuted,
          ),
        ),
      ),
    );
  }
}
