// Mocks generated by Mockito 5.4.6 from annotations
// in travelgo/test/features/flights/repositories/flight_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:travelgo/features/bookings/models/passenger.dart' as _i6;
import 'package:travelgo/features/flights/datasources/flight_remote_datasource.dart'
    as _i2;
import 'package:travelgo/features/flights/models/flight_offer.dart' as _i4;
import 'package:travelgo/features/flights/models/flight_search_query.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FlightRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightRemoteDataSource extends _i1.Mock
    implements _i2.FlightRemoteDataSource {
  @override
  _i3.Future<List<_i4.FlightOffer>> fetchFlightOffers(
          _i5.FlightSearchQuery? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFlightOffers,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i4.FlightOffer>>.value(<_i4.FlightOffer>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.FlightOffer>>.value(<_i4.FlightOffer>[]),
      ) as _i3.Future<List<_i4.FlightOffer>>);

  @override
  _i3.Future<_i4.FlightOffer?> fetchOfferDetails(String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOfferDetails,
          [offerId],
        ),
        returnValue: _i3.Future<_i4.FlightOffer?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.FlightOffer?>.value(),
      ) as _i3.Future<_i4.FlightOffer?>);

  @override
  _i3.Future<String> executeSeatHold(
    String? offerId,
    List<_i6.Passenger>? passengers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeSeatHold,
          [
            offerId,
            passengers,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #executeSeatHold,
            [
              offerId,
              passengers,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #executeSeatHold,
            [
              offerId,
              passengers,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}
